### PR TITLE
add simulate_timeseries

### PR DESCRIPTION
**Pull request by wbarhdad**
Custom user functions need three arguments: initial_abundance, n_time_points and pars. Pars is a numeric vector that has any potential parameters for a function. Not sure if this is an acceptable approach in R.

### CODE REVIEW

**Comment by wbarhdad** [comment]
@wlangera Implemented ... approach

**Comment by wlangera** [comment]
we need to change the name of the argument `temporal_autocorr`

**Comment by wlangera** [comment]
I pulled the main but there are still a lot of failures.
@Annegreet I think it is better if your work is in a separate branche because this PR is getting too big. The part of Wissam can already be implemented, but your function is still in development (as far as I can tell).

@wbarhdad and @Annegreet can you sit together and discuss how to move further? I will ask @PietrH about the check failures.

**Comment by PietrH** [comment]
3 Expectations were failing, 2 were just missing characters in the error message expectation. I fixed those. The 3rd one is more complicated: 

```
── Error ('test-simulate_timeseries.R:30:3'): arguments are of the right class ──
Error in `lambdas[i] <- lambdas[i - 1] + step`: replacement has length zero
Backtrace:
    ▆
 1. ├─testthat::expect_error(...) at test-simulate_timeseries.R:30:3
 2. │ └─testthat:::expect_condition_matching(...)
 3. │   └─testthat:::quasi_capture(...)
 4. │     ├─testthat (local) .capture(...)
 5. │     │ └─base::withCallingHandlers(...)
 6. │     └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
 7. └─simcuber::simulate_timeseries(n_time_points = 1, temporal_autocorr = simulate_random_walk)
 8.   └─simcuber (local) temporal_autocorr(initial_average_abundance, n_time_points, seed = seed) at simcuber/R/simulate_timeseries.R:196:7
 ```
 
 Failing around :
 
 https://github.com/b-cubed-eu/simcuber/blob/796d996c3d554dc4896fc41f9b64f745523b62e1/R/simulate_timeseries.R#L195-L198
 
 I'm investigating. 
 
 On a related note, the example of `simulate_timeseries()` is quite complex, and causing issues. Should we move it to a vignette instead?

**Comment by PietrH** [comment]
Actual issue is in `simulate_random_walk()`

```r

  for (i in 2:n_time_points) {
    step <- stats::rnorm(1, mean = 0, sd = sd_step)
    lambdas[i] <- lambdas[i - 1] + step
  }
```

@wlangera

**Review by wlangera — APPROVED** [review]
thanks!

**Pull request merged**
